SOURCES=$(shell echo *.cpp)
EXPORT_INCLUDES=$(shell echo *.h)

LINKED_LIBS= libMarketData libStockFighter libExchangeInterface libLevelConfig libWebSockets libThreadComms libJSON libUtils libIOInterface 

TARGET_LIB=libOrder

MODE=CPP
TAGS_FILE=stock-figher-lib-order-c++.tags
USE_JSON=YES
USE_WEB_SOCKET_CPP=YES



include ../../makefile.include
