sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-4.9
      - gfortran-4.9 
      - exuberant-ctags
      - libboost1.55-all-dev
      - valgrind
      - libncurses5-dev


before_install:
  - git submodule update --init --recursive

install:
  - pip install --user cpp-coveralls
  
script: 
  - Scripts/initModules.sh
  - g++-4.9 --version
  - TOOL_CHAIN=TRAVIS make 
  - TOOL_CHAIN=TRAVIS make memtest
  - TOOL_CHAIN=TRAVIS make clean
  - TOOL_CHAIN=TRAVIS make cover
  
after_success:
  - cd exports/objs/
  - coveralls --gcov gcov-4.9 --verbose 

