SOURCES=$(shell echo *.cpp)
EXPORT_INCLUDES=$(shell echo *.h)

LINKED_LIBS= libLevelConfig libWebSockets libThreadComms libJSON libUtils libIOInterface 

TARGET_LIB=libStockFighter

MODE=CPP
TAGS_FILE=stock-figher-libs-stockfighter-c++.tags
USE_JSON=YES
USE_WEB_SOCKET_CPP=YES
EXTERNAL_LIBS=-lssl -lcrypto



include ../../makefile.include
