SOURCES=$(shell echo *.cpp)
EXPORT_INCLUDES=$(shell echo *.h)

LINKED_LIBS= libStockFighter libExchangeInterface libLevelConfig libWebSockets libThreadComms libJSON libUtils libIOInterface 

TARGET_LIB=libMarketData

MODE=CPP
TAGS_FILE=stock-figher-libs-market-data-c++.tags
USE_JSON=YES
USE_WEB_SOCKET_CPP=YES



include ../../makefile.include
