LINKED_LIBS= libTestUtils libStockFighter \
             libExchangeInterface \
             libLevelConfig \
             libThreadComms \
             libWebSockets \
             libJSON \
             libIOInterface\
             libUtils\
			 libTest

BUILD_TIME_TESTS=quotes post_order
CPP_TAGS_FILE=stock-fighter-tests-stock-fighter-c++.tags
MODE=CPP

USE_BOOST=YES
USE_WEB_SOCKET_CPP=YES
USE_JSON=YES
USE_THREADS=YES
EXTERNAL_LIBS=-lssl -lcrypto

include ../../makefile.include
