SOURCES=$(shell echo *.cpp)
EXPORT_INCLUDES=$(shell echo *.h)

LINKED_LIBS= libWebSockets libJSON libUtils libIOInterface 

TARGET_LIB=libLevelConfig

MODE=CPP
TAGS_FILE=stock-figher-libs-config-c++.tags
USE_JSON=YES



include ../../makefile.include
